#!/bin/sh
echo ################################################
echo # Coded By DarrenRainey 15/01/2015             #
echo #################################################
apt-get update
apt-get remove zip gunzip xserver* gnome* ubuntu-desktop* zenity* yelp* xfonts* xfonts-* x11-* x11* wodim* wget vi vim gedit tar git python* python-* audio* libaudio*
